# Generated by Django 5.1.4 on 2024-12-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('area', models.IntegerField()),
                ('address', models.CharField(max_length=128)),
            ],
        ),
    ]
