# Generated by Django 5.1.4 on 2024-12-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_houses_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houses',
            old_name='banner',
            new_name='image',
        ),
    ]
