# Generated by Django 5.1.4 on 2024-12-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_alter_appointment_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
